// <auto-generated />
using System;
using GameFantasyAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GameFantasy.Migrations
{
    [DbContext(typeof(CampeonatoContexto))]
    partial class CampeonatoContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GameFantasyAPI.Model.Campeonato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Placar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Times")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ViewModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ViewModelId");

                    b.ToTable("Campeonatos");
                });

            modelBuilder.Entity("GameFantasyAPI.Model.PaginaTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Pagina")
                        .HasColumnType("int");

                    b.Property<int>("QtdPagina")
                        .HasColumnType("int");

                    b.Property<int>("TamanhoPagina")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PaginaTimes");
                });

            modelBuilder.Entity("GameFantasyAPI.Model.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaginaTimeId")
                        .HasColumnType("int");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaginaTimeId");

                    b.ToTable("Times");
                });

            modelBuilder.Entity("GameFantasyAPI.Model.Vencedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Campeao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terceiro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ViewModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ViewModelId");

                    b.ToTable("Vencedores");
                });

            modelBuilder.Entity("GameFantasyAPI.Model.ViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("ViewModels");
                });

            modelBuilder.Entity("GameFantasyAPI.Model.Campeonato", b =>
                {
                    b.HasOne("GameFantasyAPI.Model.ViewModel", null)
                        .WithMany("Campeonato")
                        .HasForeignKey("ViewModelId");
                });

            modelBuilder.Entity("GameFantasyAPI.Model.Time", b =>
                {
                    b.HasOne("GameFantasyAPI.Model.PaginaTime", null)
                        .WithMany("Itens")
                        .HasForeignKey("PaginaTimeId");
                });

            modelBuilder.Entity("GameFantasyAPI.Model.Vencedor", b =>
                {
                    b.HasOne("GameFantasyAPI.Model.ViewModel", null)
                        .WithMany("Vencedores")
                        .HasForeignKey("ViewModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
